
title: Haoyu Chen's Homepage
page-top-title: Haoyu Chen
top-section-bg-text: Computer Science
home-subtitle: Haoyu Chen&ensp;|&ensp;陈浩宇
copyright-text: '&copy; Haoyu Chen 2023. All Rights Reserved.'
